<a href="https://colab.research.google.com/github/pancholi-deep/colab-notebooks/blob/main/classification_using_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Demonstrate the classification and regression ability of a perceptron.
 - Choose a classification problem and regression problem.
 - Demonstrate the performance of perceptron on those two
   problems.
   - The iteration wise error status
   - Visualization of determinant function
  
  
Submit your Jupyter Notebook with all necessary description about the above assignment: <br>
 - Problem definition
 - necessary problem related plots
 - any thought process about perceptron tweaking
 - results of the classification and regression problem.

Design of Experiments<br>
Your presentation of results<br>
Insights and Interpretation of your results

# Classification on Breast Cancer Dataset

In [ ]:
# importing libraries
import sklearn.datasets
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("seaborn")

In [ ]:
#loading the dataset
breast_cancer = sklearn.datasets.load_breast_cancer()

In [ ]:
#setting X,Y as input data and target respectively
X = breast_cancer.data
Y = breast_cancer.target

print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [ ]:
import pandas as pd

In [ ]:
#creating a dataframe 
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

data['class'] = breast_cancer.target
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [ ]:
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [ ]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [ ]:
#dividing into train and test data
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = data.drop('class', axis=1)
Y = data['class']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify = Y, random_state=1)
print(X_train.mean(), X_test.mean(), X.mean())

mean radius                 14.058656
mean texture                19.309668
mean perimeter              91.530488
mean area                  648.097266
mean smoothness              0.096568
mean compactness             0.105144
mean concavity               0.089342
mean concave points          0.048892
mean symmetry                0.181961
mean fractal dimension       0.062979
radius error                 0.403659
texture error                1.206856
perimeter error              2.861173
area error                  39.935506
smoothness error             0.007067
compactness error            0.025681
concavity error              0.032328
concave points error         0.011963
symmetry error               0.020584
fractal dimension error      0.003815
worst radius                16.194275
worst texture               25.644902
worst perimeter            106.757715
worst area                 871.647852
worst smoothness             0.132592
worst compactness            0.257415
worst concav

In [ ]:
X_train.shape, Y_train.shape

((512, 30), (512,))

In [ ]:
X_train = X_train.values
X_test = X_test.values

In [ ]:
class Perceptron:
    # to initialize weights and threshold to None values
    def __init__ (self):
        self.w = None
        self.b = None
    
    #to return 1 if the activation function returns 1, or else return 0
    def model(self, x):
        return 1 if (np.dot(self.w, x) >= self.b) else 0
    
    # for every observation in x, calculate and return a list of predictions
    def predict(self, X):
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)
    
    #function to find the best weights and threshold vectors
    def fit(self, X, Y, epochs = 1, lr = 1):
    
        self.w = np.ones(X.shape[1])
        self.b = 0

        accuracy = {}
        max_accuracy = 0
        wt_matrix = []

        for i in range(epochs):
            for x, y in zip(X, Y):
                y_pred = self.model(x)
                if y == 1 and y_pred == 0:
                    self.w = self.w + lr * x
                    self.b = self.b - lr * 1
                elif y == 0 and y_pred == 1:
                    self.w = self.w - lr * x
                    self.b = self.b + lr * 1

            wt_matrix.append(self.w)    
            accuracy[i] = accuracy_score(self.predict(X), Y)
            if (accuracy[i] > max_accuracy):
                max_accuracy = accuracy[i]
                j = i
                chkptw = self.w
                chkptb = self.b

        #save the values of weights and threshold after all the epochs
        self.w = chkptw
        self.b = chkptb

        print(f'maximum accuracy after {epochs} epochs: {max_accuracy}')

        return np.array(wt_matrix)

In [ ]:
#new perceptron object
perceptron = Perceptron()

In [ ]:
# training with 0.3 learning rate and 5 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 5, 0.3)

maximum accuracy after 5 epochs: 0.9140625


In [ ]:
# training with 0.3 learning rate and 1000 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 1000, 0.3)

maximum accuracy after 1000 epochs: 0.935546875


In [ ]:
# training with 0.3 learning rate and 5000 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 5000, 0.3)

maximum accuracy after 5000 epochs: 0.94140625


In [ ]:
# training with 0.3 learning rate and 10000 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 10000, 0.3)

maximum accuracy after 10000 epochs: 0.947265625


In [ ]:
# training with 0.5 learning rate and 10000 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 10000, 0.5)

maximum accuracy after 10000 epochs: 0.94921875


In [ ]:
# training with 0.5 learning rate and 20000 epochs
wt_matrix = perceptron.fit(X_train, Y_train, 20000, 0.5)

maximum accuracy after 20000 epochs: 0.951171875


## Observations:

In this dataset, we are trying to classify malignant and benign cancers.
Steps:
1. loaded the data
2. defined perceptron model
3. After training, intially the error was too high. so, I tried various combinations of number of epochs and learning rate to minimize the error.
4. when we decrease the learning rate, we need to increase the number of epochs to find the best weights.
5. less learning rate and large number of epochs decreases the error, but it takes a lot of time
6. so I tried larger learning rate and lower number of epochs

The accuracy of classification model attained was better with 0.5 learning rate, keeping 20000 epochs, as compared to learning rate of 0.3, and number of epochs at 10000.